# translation table between variables names from program and Excel or HEC spreadsheet

SW_translate.csv <- textConnection(
"V.Program,  V.Excel, Comment
ANNUAL_MIN_01Day_SW,    SW_1_day_MIN
ANNUAL_MINDOY_01Day_SW, SW_1_day_MINDOY
ANNUAL_MIN_03Day_SW,    SW_3_day_MIN
ANNUAL_MINDOY_03Day_SW, SW_3_day_MINDOY
ANNUAL_MIN_07Day_SW,    SW_7_day_MIN
ANNUAL_MINDOY_07Day_SW, SW_7_day_MINDOY
ANNUAL_MIN_30Day_SW,    SW_30_day_MIN
ANNUAL_MINDOY_30Day_SW, SW_30_day_MINDOY
ANNUAL_MIN_DAILY_SW,    SW_ANNUAL_MIN
ANNUAL_MAX_DAILY_SW,    SW_ANNUAL_MAX
ANNUAL_MEAN_DAILY_SW,   SW_ANNUAL_MEAN
ANNUAL_TOTALQ_DAILY_SW, SW_ANNUAL_TOTALQ
ANNUAL_YIELDMM_DAILY_SW,SW_ANNUAL_YIELDMM
JFM_TOTALQ_DAILY_SW,    SW_JFM_TOTALQ
AMJ_TOTALQ_DAILY_SW,    SW_AMJ_TOTALQ
JAS_TOTALQ_DAILY_SW,    SW_JAS_TOTALQ
OND_TOTALQ_DAILY_SW,    SW_OND_TOTALQ
JFM_YIELDMM_DAILY_SW,   SW_JFM_YIELDMM
AMJ_YIELDMM_DAILY_SW,   SW_AMJ_YIELDMM
JAS_YIELDMM_DAILY_SW,   SW_JAS_YIELDMM
OND_YIELDMM_DAILY_SW,   SW_OND_YIELDMM
JAN_MIN_DAILY_SW,       JAN_MIN_DAILY_SW
FEB_MIN_DAILY_SW,       FEB_MIN_DAILY_SW
MAR_MIN_DAILY_SW,       MAR_MIN_DAILY_SW
APR_MIN_DAILY_SW,       APR_MIN_DAILY_SW
MAY_MIN_DAILY_SW,       MAY_MIN_DAILY_SW
JUN_MIN_DAILY_SW,       JUN_MIN_DAILY_SW
JUL_MIN_DAILY_SW,       JUL_MIN_DAILY_SW
AUG_MIN_DAILY_SW,       AUG_MIN_DAILY_SW
SEP_MIN_DAILY_SW,       SEPT_MIN_DAILY_SW, # Notice SEPT vs SEP
OCT_MIN_DAILY_SW,       OCT_MIN_DAILY_SW
NOV_MIN_DAILY_SW,       NOV_MIN_DAILY_SW
DEC_MIN_DAILY_SW,       DEC_MIN_DAILY_SW
JAN_MAX_DAILY_SW,       JAN_MAX_DAILY_SW
FEB_MAX_DAILY_SW,       FEB_MAX_DAILY_SW
MAR_MAX_DAILY_SW,       MAR_MAX_DAILY_SW
APR_MAX_DAILY_SW,       APR_MAX_DAILY_SW
MAY_MAX_DAILY_SW,       MAY_MAX_DAILY_SW
JUN_MAX_DAILY_SW,       JUN_MAX_DAILY_SW
JUL_MAX_DAILY_SW,       JUL_MAX_DAILY_SW
AUG_MAX_DAILY_SW,       AUG_MAX_DAILY_SW
SEP_MAX_DAILY_SW,       SEPT_MAX_DAILY_SW, # Notice SEPT vs SEP
OCT_MAX_DAILY_SW,       OCT_MAX_DAILY_SW
NOV_MAX_DAILY_SW,       NOV_MAX_DAILY_SW
DEC_MAX_DAILY_SW,       DEC_MAX_DAILY_SW
JAN_MEAN_DAILY_SW,      JAN_MEAN_SW
FEB_MEAN_DAILY_SW,      FEB_MEAN_SW
MAR_MEAN_DAILY_SW,      MAR_MEAN_SW
APR_MEAN_DAILY_SW,      APR_MEAN_SW
MAY_MEAN_DAILY_SW,      MAY_MEAN_SW
JUN_MEAN_DAILY_SW,      JUN_MEAN_SW
JUL_MEAN_DAILY_SW,      JUL_MEAN_SW
AUG_MEAN_DAILY_SW,      AUG_MEAN_SW
SEP_MEAN_DAILY_SW,      SEP_MEAN_SW
OCT_MEAN_DAILY_SW,      OCT_MEAN_SW
NOV_MEAN_DAILY_SW,      NOV_MEAN_SW
DEC_MEAN_DAILY_SW,      DEC_MEAN_SW
JAN_P50_DAILY_SW,       JAN_P50_SW
FEB_P50_DAILY_SW,       FEB_P50_SW
MAR_P50_DAILY_SW,       MAR_P50_SW
APR_P50_DAILY_SW,       APR_P50_SW
MAY_P50_DAILY_SW,       MAY_P50_SW
JUN_P50_DAILY_SW,       JUN_P50_SW
JUL_P50_DAILY_SW,       JUL_P50_SW
AUG_P50_DAILY_SW,       AUG_P50_SW
SEP_P50_DAILY_SW,       SEP_P50_SW
OCT_P50_DAILY_SW,       OCT_P50_SW
NOV_P50_DAILY_SW,       NOV_P50_SW
DEC_P50_DAILY_SW,       DEC_P50_SW
JAN_P80_DAILY_SW,       JAN_P80_SW
FEB_P80_DAILY_SW,       FEB_P80_SW
MAR_P80_DAILY_SW,       MAR_P80_SW
APR_P80_DAILY_SW,       APR_P80_SW
MAY_P80_DAILY_SW,       MAY_P80_SW
JUN_P80_DAILY_SW,       JUN_P80_SW
JUL_P80_DAILY_SW,       JUL_P80_SW
AUG_P80_DAILY_SW,       AUG_P80_SW
SEP_P80_DAILY_SW,       SEP_P80_SW
OCT_P80_DAILY_SW,       OCT_P80_SW
NOV_P80_DAILY_SW,       NOV_P80_SW
DEC_P80_DAILY_SW,       DEC_P80_SW
JAN_P90_DAILY_SW,       JAN_P90_SW
FEB_P90_DAILY_SW,       FEB_P90_SW
MAR_P90_DAILY_SW,       MAR_P90_SW
APR_P90_DAILY_SW,       APR_P90_SW
MAY_P90_DAILY_SW,       MAY_P90_SW
JUN_P90_DAILY_SW,       JUN_P90_SW
JUL_P90_DAILY_SW,       JUL_P90_SW
AUG_P90_DAILY_SW,       AUG_P90_SW
SEP_P90_DAILY_SW,       SEP_P90_SW
OCT_P90_DAILY_SW,       OCT_P90_SW
NOV_P90_DAILY_SW,       NOV_P90_SW
DEC_P90_DAILY_SW,       DEC_P90_SW
Oct_to_Sep_TOTALQ_DAILY_SW, SW_Oct_to_Sept_TOTALQ
Oct_to_Sep_YIELDMM_DAILY_SW, SW_Oct_to_Sept_YIELDMM
AMJJAS_TotalQ_DAILY_SW, SW_AMJJAS_TotalQ 
ONDJFM_TotalQ_DAILY_SW, SW_ONDJFM_TotalQ
AMJJAS_YIELDMM_DAILY_SW,SW_AMJJAS_YIELDMM 
ONDJFM_YIELDMM_DAILY_SW,SW_ONDJFM_YIELDMM
ANNUAL_CUMQ_DAILY_SW,   SW_TOTAL_Q_CMS
ANNUAL_Date_25P_CUMQ_DAILY_SW, Date_25P_cummul_Q,
ANNUAL_Date_50P_CUMQ_DAILY_SW, Date_50P_cummul_Q,
ANNUAL_Date_75P_CUMQ_DAILY_SW, Date_75P_cummul_Q")
SW_translate<- read.csv(SW_translate.csv, header=TRUE, as.is=TRUE, strip.white=TRUE)
