# Copyright 2017 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

# translation table between variables names from program and Excel or HEC spreadsheet

SW_translate.csv <- textConnection(
"V.Program,  V.Excel, Comment
CY_MIN_01Day_SW,    SW_1_day_MIN
CY_MINDOY_01Day_SW, SW_1_day_MINDOY
CY_MIN_03Day_SW,    SW_3_day_MIN
CY_MINDOY_03Day_SW, SW_3_day_MINDOY
CY_MIN_07Day_SW,    SW_7_day_MIN
CY_MINDOY_07Day_SW, SW_7_day_MINDOY
CY_MIN_30Day_SW,    SW_30_day_MIN
CY_MINDOY_30Day_SW, SW_30_day_MINDOY
CY_MIN_DAILY_SW,    SW_ANNUAL_MIN
CY_MAX_DAILY_SW,       SW_ANNUAL_MAX
CY_MEAN_DAILY_SW,      SW_ANNUAL_MEAN
CY_TOTALQ_DAILY_SW,    SW_ANNUAL_TOTALQ
CY_YIELDMM_DAILY_SW,   SW_ANNUAL_YIELDMM
JFM_TOTALQ_DAILY_SW,    SW_JFM_TOTALQ
AMJ_TOTALQ_DAILY_SW,    SW_AMJ_TOTALQ
JAS_TOTALQ_DAILY_SW,    SW_JAS_TOTALQ
OND_TOTALQ_DAILY_SW,    SW_OND_TOTALQ
JFM_YIELDMM_DAILY_SW,   SW_JFM_YIELDMM
AMJ_YIELDMM_DAILY_SW,   SW_AMJ_YIELDMM
JAS_YIELDMM_DAILY_SW,   SW_JAS_YIELDMM
OND_YIELDMM_DAILY_SW,   SW_OND_YIELDMM
JAN_MIN_DAILY_SW,       JAN_MIN_DAILY_SW
FEB_MIN_DAILY_SW,       FEB_MIN_DAILY_SW
MAR_MIN_DAILY_SW,       MAR_MIN_DAILY_SW
APR_MIN_DAILY_SW,       APR_MIN_DAILY_SW
MAY_MIN_DAILY_SW,       MAY_MIN_DAILY_SW
JUN_MIN_DAILY_SW,       JUN_MIN_DAILY_SW
JUL_MIN_DAILY_SW,       JUL_MIN_DAILY_SW
AUG_MIN_DAILY_SW,       AUG_MIN_DAILY_SW
SEP_MIN_DAILY_SW,       SEPT_MIN_DAILY_SW, # Notice SEPT vs SEP
OCT_MIN_DAILY_SW,       OCT_MIN_DAILY_SW
NOV_MIN_DAILY_SW,       NOV_MIN_DAILY_SW
DEC_MIN_DAILY_SW,       DEC_MIN_DAILY_SW
JAN_MAX_DAILY_SW,       JAN_MAX_DAILY_SW
FEB_MAX_DAILY_SW,       FEB_MAX_DAILY_SW
MAR_MAX_DAILY_SW,       MAR_MAX_DAILY_SW
APR_MAX_DAILY_SW,       APR_MAX_DAILY_SW
MAY_MAX_DAILY_SW,       MAY_MAX_DAILY_SW
JUN_MAX_DAILY_SW,       JUN_MAX_DAILY_SW
JUL_MAX_DAILY_SW,       JUL_MAX_DAILY_SW
AUG_MAX_DAILY_SW,       AUG_MAX_DAILY_SW
SEP_MAX_DAILY_SW,       SEPT_MAX_DAILY_SW, # Notice SEPT vs SEP
OCT_MAX_DAILY_SW,       OCT_MAX_DAILY_SW
NOV_MAX_DAILY_SW,       NOV_MAX_DAILY_SW
DEC_MAX_DAILY_SW,       DEC_MAX_DAILY_SW
JAN_MEAN_DAILY_SW,      JAN_MEAN_SW
FEB_MEAN_DAILY_SW,      FEB_MEAN_SW
MAR_MEAN_DAILY_SW,      MAR_MEAN_SW
APR_MEAN_DAILY_SW,      APR_MEAN_SW
MAY_MEAN_DAILY_SW,      MAY_MEAN_SW
JUN_MEAN_DAILY_SW,      JUN_MEAN_SW
JUL_MEAN_DAILY_SW,      JUL_MEAN_SW
AUG_MEAN_DAILY_SW,      AUG_MEAN_SW
SEP_MEAN_DAILY_SW,      SEP_MEAN_SW
OCT_MEAN_DAILY_SW,      OCT_MEAN_SW
NOV_MEAN_DAILY_SW,      NOV_MEAN_SW
DEC_MEAN_DAILY_SW,      DEC_MEAN_SW
JAN_P50_DAILY_SW,       JAN_P50_SW
FEB_P50_DAILY_SW,       FEB_P50_SW
MAR_P50_DAILY_SW,       MAR_P50_SW
APR_P50_DAILY_SW,       APR_P50_SW
MAY_P50_DAILY_SW,       MAY_P50_SW
JUN_P50_DAILY_SW,       JUN_P50_SW
JUL_P50_DAILY_SW,       JUL_P50_SW
AUG_P50_DAILY_SW,       AUG_P50_SW
SEP_P50_DAILY_SW,       SEP_P50_SW
OCT_P50_DAILY_SW,       OCT_P50_SW
NOV_P50_DAILY_SW,       NOV_P50_SW
DEC_P50_DAILY_SW,       DEC_P50_SW
JAN_P20_DAILY_SW,       JAN_P80_SW
FEB_P20_DAILY_SW,       FEB_P80_SW
MAR_P20_DAILY_SW,       MAR_P80_SW
APR_P20_DAILY_SW,       APR_P80_SW
MAY_P20_DAILY_SW,       MAY_P80_SW
JUN_P20_DAILY_SW,       JUN_P80_SW
JUL_P20_DAILY_SW,       JUL_P80_SW
AUG_P20_DAILY_SW,       AUG_P80_SW
SEP_P20_DAILY_SW,       SEP_P80_SW
OCT_P20_DAILY_SW,       OCT_P80_SW
NOV_P20_DAILY_SW,       NOV_P80_SW
DEC_P20_DAILY_SW,       DEC_P80_SW
JAN_P10_DAILY_SW,       JAN_P90_SW
FEB_P10_DAILY_SW,       FEB_P90_SW
MAR_P10_DAILY_SW,       MAR_P90_SW
APR_P10_DAILY_SW,       APR_P90_SW
MAY_P10_DAILY_SW,       MAY_P90_SW
JUN_P10_DAILY_SW,       JUN_P90_SW
JUL_P10_DAILY_SW,       JUL_P90_SW
AUG_P10_DAILY_SW,       AUG_P90_SW
SEP_P10_DAILY_SW,       SEP_P90_SW
OCT_P10_DAILY_SW,       OCT_P90_SW
NOV_P10_DAILY_SW,       NOV_P90_SW
DEC_P10_DAILY_SW,       DEC_P90_SW
WY_TOTALQ_DAILY_SW,   SW_Oct_to_Sept_TOTALQ
WY_YIELDMM_DAILY_SW,  SW_Oct_to_Sept_YIELDMM
AMJJAS_TotalQ_DAILY_SW, SW_AMJJAS_TotalQ
ONDJFM_TotalQ_DAILY_SW, SW_ONDJFM_TotalQ
AMJJAS_YIELDMM_DAILY_SW,SW_AMJJAS_YIELDMM
ONDJFM_YIELDMM_DAILY_SW,SW_ONDJFM_YIELDMM
CY_CUMQ_DAILY_SW,       SW_TOTAL_Q_CMS
CY_DATE_25P_CUMQ_DAILY_SW, DATE_25P_CUMMUL_Q
CY_DATE_50P_CUMQ_DAILY_SW, DATE_50P_CUMMUL_Q
CY_DATE_75P_CUMQ_DAILY_SW, DATE_75P_CUMMUL_Q")

SW_translate<- read.csv(SW_translate.csv, header=TRUE, as.is=TRUE, strip.white=TRUE)
